# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5d3d3b9827fa18886396a13132912bb808d1c88f6cab85f2d767df7495fab6a782de234df9fe74c08fcc2ea18623a576409645f4bc24f72f1c76664bed22453

test:
  secret_key_base: f8bed580e9660ae52fc11a442ba863191267cee0c39cace66507d1ba2af1c3924f1b9ef7627d074e0a99295015a5eaa21babcdcb7549725f482864e63e07823b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
